### ISSUE TITLE
New instance

### ISSUE THREAD

**Issue by r2fo** [zyachel/quetre#122]
Can you please add my instance to the list?

URL: https://quetre.r4fo.com
Country: The Netherlands
Provider: Oracle
Cloudflare: false

**Comment by zyachel** [comment]
done, thanks!

**Comment by zyachel** [comment]
you can use a single container. that env var is just for disabling the [csp header that tells browsers to upgrade links in the page](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/upgrade-insecure-requests).  
but since you have both hsts and nginx redirect, I don't think it'll matter much.
